### ISSUE TITLE
Luakit doesnt give a search result in this project

### ISSUE THREAD

**Issue by o-jasper** [skx/lumail#237]
So here is one.

Should be fairly easy to make a chrome page, for instance [starting with this](https://github.com/mason-larobina/luakit/wiki/Minimal-chrome-page). Perhaps also nice to stuff things into an SQL table for it? I have a [thingy to search those nicely](https://github.com/o-jasper/o-jasper-luakit-stuff/tree/master/listview), but it still needs work.

**Comment by jugglerchris** [comment]
Sorry if I'm missing something, but what's the relevance of Luakit to lumail?

**Comment by o-jasper** [comment]
Could make an interface with it. Maybe relevance is relatively low.
