### ISSUE TITLE
Attachment names not shown

### ISSUE THREAD

**Issue by jugglerchris** [skx/lumail#241]
In the attachment list, I get a mix of "inline-part-N" and blank names.  I think this is due to a typo - the following seems to fix it:
```diff
--- a/src/message.cc
+++ b/src/message.cc
@@ -1440,7 +1440,7 @@ bool CMessage::parse_attachments()
             if ( ( view_inline == true ) ||
                  ( view_inline == false && ( is_inline == false ) ) )
             {
-                CAttachment *foo = new CAttachment( tmp, (void *)adata,(size_t ) len );
+                CAttachment *foo = new CAttachment( aname, (void *)adata,(size_t ) len );
                 m_attachments.push_back(foo);
             }
         }
```
Chris

**Comment by jugglerchris** [comment]
I can do this as a proper pull request when I get a bit of time at home.  :-)

**Comment by trou** [comment]
Should be fixed, thanks for the report. Reopen if not :)

**Comment by skx** [comment]
Thanks for your prompt attention - I've been distracted recently, but I should be more involved in the near future.
